### PR TITLE
Allow usage of absolute time (hour:minute) when starting or stopping time tracking

### PR DESCRIPTION
**Pull request by dribnif**
The change is non-breaking and does not negatively impact
existing functionality. (Adding relative time still works)

Example usage:
```
$ ti on 'very secret undertaking' 13:15
Start working on very secret undertaking.
$ ti fin 13:30
So you stopped working on very secret undertaking.
$ ti log
very secret undertaking  ∙∙  15 minutes
```

### CODE REVIEW

**Comment by dribnif** [comment]
I failed to execute the automated tests on my machine and therefore refrained from using them as a basis for the feature development. Maybe add some documentation about getting them running to the README? I am indeed ashamed of myself for taking this horrendous shortcut, but the functionality was more important to me.

**Comment by tbekolay** [comment]
No worries about the tests; I should set them up to run on TravisCI anyhow.

One request though, right now this pull request is made from your `master` branch. GitHub keeps track of your master branch as it changes, so all of the commits you've pushed to your `master` are showing up in this PR. Are all of these commits part of this PR, or just some of them?

**Comment by dribnif** [comment]
Oh. I wasn't aware of the fact that the pull request tracks the entire branch.

I really got into modifying ti to suit my personal needs a lot. In doing so, I realized I am following an entirely different design philosophy to that on which ti builds. I need powerful reporting and aggregations and hence a focus on absolute time entries, as opposed to the relative ones which ti is based upon. I also expect more verbosity from the tool to give the user more context. 

After talking with some colleagues and users of the burgeoning functionality I implemented, I arrived to the conclusion that a fork is the right way to go here.

My immediate goals will be modularization to improve maintainability. I will also add some more reporting functionality

I therefore propose you reject this pull request, as it is not really in line with the design philosophy of ti.

Thanks

Max

**Comment by tbekolay** [comment]
Okay, I understand where you're coming from. I also would like to modularize to improve maintainability, but don't have much time to devote to `ti` at the moment. Regardless, it is definitely easier for you to fork and develop on your own with a repo you control, so all the best for your fork :)

Do you mind if I cherry pick in the first commit, which was the content of the original pull request? It's a non-breaking and useful improvement, so I think it would be great to have, but I don't want to pull it in without your OK.

**Comment by dribnif** [comment]
Sure thing. Knock yourself out. Just be aware it is in fact breaking some basic asumptions under the hood: (took me a while to figure it out.)

I just saved the absolute time without any regards to the timezone. I'm living in the CET (winter time at the moment) timezone. Every other DB-entry is made in UTC.

So let's imagine i put in `ti start project 7:00`. This gets saved as 07:00 in the DB. I then go ahead and half an hour later say 'ti stop' with the implicit time argument 'now'. It will store that as 06:30 in the DB because it uses UTC. 

I have addressed the issue in other later commits though. 

Don't you just love handling timezones in code? :)

**Comment by tbekolay** [comment]
> Don't you just love handling timezones in code? :)

It's the best ;) Thanks for the heads up about the timezones. I think for now I'll close this and think about how to proceed when I get some time to devote to `ti`.

**Comment by dribnif** [comment]
I will try and maintain existing ti features in parallel to existing functionality. I will get back to you when I have a release ready. Maybe you'll like some features and integrate them back into the app.

**Comment by tbekolay** [comment]
Sounds good! Thanks :)

**Pull request closed without merging**
